# Generated by Django 3.1 on 2020-08-21 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_auto_20200821_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 12, 10, 56, 790214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 12, 10, 56, 789218, tzinfo=utc)),
        ),
    ]
